### ISSUE TITLE
[INFO] buat android ada 2 apl sederhana

### ISSUE THREAD

**Issue by FONZACUS** [bebasid/bebasit#10]
maaf ya kalo salah tempat, masih git noob saya

buat android ada 2 apl sederhana buat lewati dpi, [intra](https://play.google.com/store/apps/details?id=app.intra)
sama [unicorn](https://play.google.com/store/apps/details?id=kr.co.lylstudio.httpsguard)
[iphone](
https://apps.apple.com/app/unicorn-https/id1466584968)

imho lebih bagus intra, ada banyak setting dns + bisa nambah custom server. unicorn cuma bisa 2

tinggal diaktifin bisa langsung, buat di win + mac ada clientnya di situs mereka - menu - product - unicorn https
https://getunicorn.app/en

mungkin ada yang bisa bikin fork buat client pc dkk tapi bisa ambil racikan anti sni + dpi mereka. liat: di intra kaya ga nemu racikannya

**Comment by icaksh** [comment]
win udh ada (bebasit)
linux dan mac bebasit masih pakai cli.
untuk mac masih belum dapat di build untuk GUInya karena kendala Apple Developer Account

android dulu sudah ada (PowerTunnel) tapi entah sekarang gimana nasibnya

thanks sarannya buat intra, bisa ngebuild aslinya (karena open source) tapi proses rekode masih ada kendala karena keterbatasan sumber daya dari KINI

**Comment by FONZACUS** [comment]
iya dulu pernah nyoba power, dpitunnel sama invizible buat android, udah kurang kuat karena sni + dpi. untungnya intra masih ada perkembangan. di changelog terbaru ada info tls client hello fragmentation (apaan tuh? anti dpi baru baca: sekilas)

moga aja buat ke depannya bisa jadi rebase ke intra kalo butuh yang lebih
