### ISSUE TITLE
Customize site benchmark untuk proxy tunnel

### ISSUE THREAD

**Issue by fijar-lazuardy** [bebasid/bebasit#3]
moved from bebasid

Berhubung netflix udah ga diblokir sama hampir semua ISP, kalo user bisa set sendiri site buat jadi "benchmark" untuk proxy tunnel-nya (misal yang default-nya netflix, jadi reddit) pasti lebih mantep

**Comment by ryukora** [comment]
netflix sudah buka ya, utk reddit silakan pake doh/dot sementara
